### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wephy** [wephy/project-euler#2]
### TODO

Milestones:
- [x] Complete first 100 problems
- [ ] Complete first 200 problems

Tasks:
- [ ] Optimise p057
- [ ] Optimise p066 to use Chakravāla's method
- [x] Optimise p068
- [ ] Fix p078 to not make any assumptions (current solution relies on assuming solution is under 100,000)
- [ ] Fix p079 to not make any assumptions (currently assumes sufficient data and that digits only appear once - I have a working but slow fix: create while loop to test all integers until one is found that passes all test cases (indexes exist in order)
- [ ] p096 is currently too slow (~5 seconds)
